version: "3"

services:
  rng:
    image: looztra/dockercoinsextract_rng:1.0
    deploy:
      mode: global
    networks:
      - dockercoins

  hasher:
    image: looztra/dockercoinsextract_hasher:1.0
    deploy:
      replicas: 1
    networks:
      - dockercoins

  webui:
    image: looztra/dockercoinsextract_webui:1.0
    deploy:
      replicas: 1
    ports:
      - "80:80"
    networks:
      - dockercoins

  redis:
    image: redis:3-alpine
    networks:
      - dockercoins

  worker:
    image: looztra/dockercoinsextract_worker:1.0
    deploy:
      replicas: 4
    networks:
      - dockercoins

networks:
  dockercoins:
