---
kind: Namespace
apiVersion: v1
metadata:
  name: dockercoins
  labels:
    name: dockercoins

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dockercoins
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: dockercoins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3-alpine
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: rng
  namespace: dockercoins
  labels:
    app: rng
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: rng
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: rng
  namespace: dockercoins
spec:
  template:
    metadata:
      labels:
        app: rng
    spec:
      nodeSelector:
        app: rng-node
      containers:
      - name: rng
        image: looztra/dockercoinsextract_rng:1.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hasher
  namespace: dockercoins
  labels:
    app: hasher
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: hasher
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hasher
  namespace: dockercoins
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - name: hasher
        image: looztra/dockercoinsextract_hasher:1.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: dockercoins
  labels:
    app: worker
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: worker
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: dockercoins
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: looztra/dockercoinsextract_worker:1.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: dockercoins
  labels:
    app: webui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: webui
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webui
  namespace: dockercoins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: looztra/dockercoinsextract_webui:1.0
        ports:
        - containerPort: 80
