---
apiVersion: v1
kind: Service
metadata:
  name: hasher
  namespace: dockercoins
  labels:
    app: hasher
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: hasher
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hasher
  namespace: dockercoins
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - name: hasher
        image: looztra/dockercoinsextract_hasher:1.0
        ports:
        - containerPort: 80
