---
apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: dockercoins
  labels:
    app: webui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: webui
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webui
  namespace: dockercoins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: looztra/dockercoinsextract_webui:1.0
        ports:
        - containerPort: 80
