---
apiVersion: v1
kind: Service
metadata:
  name: webcounter
  namespace: webcounter
  labels:
    app: webcounter
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 80
    protocol: TCP
  selector:
    app: webcounter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webcounter
  namespace: webcounter
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: webcounter
    spec:
      containers:
      - name: webcounter
        image: looztra/webcounter:1.0
        ports:
        - containerPort: 80
